name: 'go-test-report'
description: 'Run go tests and generate a report'
branding:
  icon: 'bar-chart'
  color: 'green'
inputs:
  packages:
    description: 'Go packages test.'
    required: false
    default: './...'
  reports_only:
    description: 'Generate test reports only. Does not fail action on failed tests.'
    required: false
    default: 'false'
  summary:
    description: 'Display test results in a step summary.'
    required: false
    default: 'true'
  GO111MODULE:
    description: 'Set the GO111MODULE go env variable.'
    required: false
    default: 'auto'
outputs:
  json-report:
    description: 'The json report'
  junit-report:
    description: 'The junit xml report'
  markdown-report:
    description: 'The markdown report'
runs:
  using: 'docker'
  image: 'src/Dockerfile'
  args:
    - ${{ inputs.modules }}