name: Test Action

on:
  - push
  - workflow_dispatch

jobs:
  run-passing-test:
    runs-on: ubuntu-latest
    name: Test main module
    steps:
      - uses: actions/setup-go@v4
      - uses: actions/checkout@v3
      - name: brian-pickens/go-test-report
        id: test
        uses: ./
        with:
          packages: ./test
      - name: Output Reports
        run: |
          echo -e "$json"
          echo -e "$junit"
          echo -e "$markdown"
        env:
          json: ${{ steps.test.outputs.json-report }}
          junit: ${{ steps.test.outputs.junit-report }}
          markdown: ${{ steps.test.outputs.markdown-report }}
    #   - name: Summary
    #     if: always()
    #     run: echo ${test_summary} >> $GITHUB_STEP_SUMMARY
    #     env:
    #       test_summary: ${{ steps.test.outputs.markdown-report }} 