name: Test Action

on:
  - push
  - workflow_dispatch

jobs:
  with-summary:
    runs-on: ubuntu-latest
    name: With Summary
    steps:
      - uses: actions/setup-go@v4
      - uses: actions/checkout@v3
      - name: brian-pickens/go-test-report
        id: test
        uses: ./
        with:
          packages: ./test
  withjout-summary:
    runs-on: ubuntu-latest
    name: Without Summary
    steps:
      - uses: actions/setup-go@v4
      - uses: actions/checkout@v3
      - name: brian-pickens/go-test-report
        id: test
        uses: ./
        with:
          packages: ./test
          summary: false
      - name: Output Reports
        if: always()
        run: |
            echo -e "$json"
            echo -e "$junit"
            echo -e "$markdown"
        env:
            json: ${{ steps.test.outputs.json-report }}
            junit: ${{ steps.test.outputs.junit-report }}
            markdown: ${{ steps.test.outputs.markdown-report }}

  reports-only:
    runs-on: ubuntu-latest
    name: Reports Only
    steps:
      - uses: actions/setup-go@v4
      - uses: actions/checkout@v3
      - name: brian-pickens/go-test-report
        id: test
        uses: ./
        with:
          packages: ./test
          reports-only: true
          summary: false
      - name: Output Reports
        if: always()
        run: |
            echo -e "$json"
            echo -e "$junit"
            echo -e "$markdown"
        env:
            json: ${{ steps.test.outputs.json-report }}
            junit: ${{ steps.test.outputs.junit-report }}
            markdown: ${{ steps.test.outputs.markdown-report }}